[tool.poetry]
name = "swanti"
version = "0.1.0"
description = "TSP SWAN script (Experimental)"
authors = ["USoVietnam"]
license = "MIT"

[tool.poetry.dependencies]
python = "^3.9"
google-api-python-client = "^2.9.0"
Pillow = "^8.2.0"
pyimgur = "^0.6.0"
pygraphviz = "^1.7"
networkx = "^2.5.1"
requests = "^2.25.1"
oauth2client = "^4.1.3"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
